# load("@bazel_tools//tools/cpp:cc_toolchain_config.bzl", "cc_toolchain_config")

# register_toolchains("//crosstool:rocm-toolchain-suite")

new_local_repository(
    name = "rocm-repo",
    path = "/opt/rocm",
    build_file_content = """
cc_library(
    name = "hip",
    hdrs = glob(["include/**/*.h"]),
    includes = ["include"],
    visibility = ["//visibility:public"],
)
""",
)


new_local_repository(
    name = "gpu-common",
    path = "/data/Playground/",
    build_file_content = """
cc_library(
    name = "common",
    hdrs = glob(["common/*.h", "common/*.hpp"]),
    srcs = glob(["common/*.cc"]),
    visibility = ["//visibility:public"],
    deps = ["@rocm-repo//:hip"],
)
""",
)
